const router = require("express").Router();
const categoryRouter = require("./category.routes");
const districtRouter = require("./district.routes");
const imageRouter = require("./image.routes");
const regionRouter = require("./region.routes");
const comissionRouter = require("./comission.routes");
const statusRouter = require("./status.routes");
const userRouter = require("./user.routes");
const userAddressRouter = require("./user_location.routes");
const machineRouter = require("./machine.routes");
const roleRouter = require("./roles.routes");
const userRoleRouter = require("./user-roles.routes");
const authRouter = require("./auth.routes");
const paymentRouter = require("./payment.routes");
const reviewRouter = require("./reviews.routes");
const contractRouter = require("./contract.routes");

router.use("/category", categoryRouter);
router.use("/district", districtRouter);
router.use("/image", imageRouter);
router.use("/region", regionRouter);
router.use("/status", statusRouter);
router.use("/comission", comissionRouter);
router.use("/users", userRouter);
router.use("/user_location", userAddressRouter);
router.use("/machine", machineRouter);
router.use("/role", roleRouter);
router.use("/user-role", userRoleRouter);
router.use("/auth", authRouter);
router.use("/contract", contractRouter);
router.use("/payment", paymentRouter);
router.use("/review", reviewRouter);

module.exports = router;
